name: Docker Image CI

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

env:
  REPO_NAME: ${{ github.repository }}

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Get VERSION
      id: version
      run: echo "version=$(cat VERSION)" >> $GITHUB_OUTPUT

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build the Docker image
      run: |
        docker build . --file docker/remeta.dockerfile --tag ghcr.io/${{ env.REPO_NAME }}/remeta:v${{ steps.version.outputs.version }}
        docker push ghcr.io/${{ env.REPO_NAME }}/remeta:v${{ steps.version.outputs.version }}
